sparql-endpoint:
  query-url: URL of SPARQL 1.1 Query endpoint
  update-url: URL of SPARQL 1.1 Update endpoint
  username: Update endpoint's user name
  page-size: # number of bindings to be processed at once
    query: 5000 # page-size for SPARQL queries
    update: 5000 # page-size for SPARQL updates
  parallel-execution: true # should the SPARQL queries be executed in parallel?
  password: Update endpoint's password
  retry-count: 5 # maximum number of times SPARQL queries can be retried
features:
  source-graph: URI of the named graph to process
  classes: # List of absolute URIs of classes 
    - http://some.example.class
  properties: # Lists of absolute URIs of properties 
    inbound:
      - http://inbound.property
    outbound:
      - http://outbound.property
